apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "event-listener.fullname" . }}
  labels:
    {{- include "event-listener.labels" . | nindent 4 }}
    {{- include "event-listener.datadogLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "event-listener.selectorLabels" . | nindent 6 }}
      {{- include "event-listener.datadogSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "event-listener.selectorLabels" . | nindent 8 }}
        {{- include "event-listener.datadogSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ORDER_CONTRACT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: orderContractAddress
                  name: {{ include "event-listener.fullname" . }}
            - name: WHITELIST_CONTRACT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: whitelistContractAddresses
                  name: {{ include "event-listener.fullname" . }}
            - name: EXCHANGE_CONTRACT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: exchangeContractAddress
                  name: {{ include "event-listener.fullname" . }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: awsAccessKeyId
                  name: {{ include "event-listener.fullname" . }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: awsSecretAccessKey
                  name: {{ include "event-listener.fullname" . }}
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  key: awsRegion
                  name: {{ include "event-listener.fullname" . }}
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: chainId
                  name: {{ include "event-listener.fullname" . }}
            - name: WEB3_PROVIDER
              valueFrom:
                configMapKeyRef:
                  key: web3Provider
                  name: {{ include "event-listener.fullname" . }}
            - name: ALCHEMY_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: alchemyApiKey
                  name: {{ include "event-listener.fullname" . }}
            - name: ALCHEMY_HTTP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: alchemyHttpEndpoint
                  name: {{ include "event-listener.fullname" . }}
            - name: ALCHEMY_WS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: alchemyWsEndpoint
                  name: {{ include "event-listener.fullname" . }}
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  key: awsRegion
                  name: {{ include "event-listener.fullname" . }}
            - name: NEW_BLOCK_HEADERS_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: newBlockHeadersQueueUrl
                  name: {{ include "event-listener.fullname" . }}
            - name: NFT_TRANSFER_EVENT_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: nftTransferEventQueueUrl
                  name: {{ include "event-listener.fullname" . }}
            - name: ORDER_CANCELLED_EVENT_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: orderCancelledEventQueueUrl
                  name: {{ include "event-listener.fullname" . }}
            - name: ORDER_FULFILLED_EVENT_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: orderFulfilledEventQueueUrl
                  name: {{ include "event-listener.fullname" . }}
            - name: OWNERSHIP_TRANSFERRED_EVENT_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: ownershipTransferredEventQueueUrl
                  name: {{ include "event-listener.fullname" . }}
            - name: EXCHANGE_EVENT_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: exchangeEventQueueUrl
                  name: {{ include "event-listener.fullname" . }}
            - name: ORDER_CANCELLED_EVENT_RETRY_COUNT
              valueFrom:
                configMapKeyRef:
                  key: orderCancelledEventRetryCount
                  name: {{ include "event-listener.fullname" . }}
            - name: ORDER_FULFILLED_EVENT_RETRY_COUNT
              valueFrom:
                configMapKeyRef:
                  key: orderFulfilledEventRetryCount
                  name: {{ include "event-listener.fullname" . }}
            - name: DB_ENGINE
              valueFrom:
                configMapKeyRef:
                  key: dbEngine
                  name: {{ include "event-listener.fullname" . }}
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: dbPort
                  name: {{ include "event-listener.fullname" . }}
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: dbDatabase
                  name: {{ include "event-listener.fullname" . }}
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: dbPassword
                  name: {{ include "event-listener.fullname" . }}
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: dbHost
                  name: {{ include "event-listener.fullname" . }}
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: dbUser
                  name: {{ include "event-listener.fullname" . }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_PROFILING_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: ddProfilingEnabled
                  name: {{ include "event-listener.fullname" . }}-datadog
            - name: DD_LOGS_INJECTION
              valueFrom:
                configMapKeyRef:
                  key: ddLogsInjectionEnabled
                  name: {{ include "event-listener.fullname" . }}-datadog
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
