apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payment.fullname" . }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}
    {{- include "payment.datadogLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "payment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "payment.selectorLabels" . | nindent 8 }}
        {{- include "payment.datadogSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  key: backendHost
                  name: {{ include "payment.fullname" . }}-common
            - name: FRONTEND_HOST
              valueFrom:
                configMapKeyRef:
                  key: frontendHost
                  name: {{ include "payment.fullname" . }}-common
            - name: ORIGINALS_HOST
              valueFrom:
                configMapKeyRef:
                  key: originalsHost
                  name: {{ include "payment.fullname" . }}-common
            - name: INAPP_HOST
              valueFrom:
                configMapKeyRef:
                  key: inAppHost
                  name: {{ include "payment.fullname" . }}-common
            - name: ADMIN_WALLET_HOST
              valueFrom:
                configMapKeyRef:
                  key: adminWalletHost
                  name: {{ include "payment.fullname" . }}-common
            - name: ETHERS_NETWORK
              valueFrom:
                configMapKeyRef:
                  key: ethereumNetwork
                  name: {{ include "payment.fullname" . }}-common
            - name: RAPID_CRAWLING_COLLECTION_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingCollectionQueueName
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_COLLECTION_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingCollectionQueueUrl
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_ITEM_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingItemQueueName
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_ITEM_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingItemQueueUrl
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_REFRESH_ITEM_META_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingRefreshItemMetaQueueName
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_REFRESH_ITEM_META_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingRefreshItemMetaQueueUrl
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: CHECK_STATUS_OF_AIRDROP_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: checkStatusOfAirdropQueueName
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: CHECK_STATUS_OF_AIRDROP_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: checkStatusOfAirdropQueueUrl
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: BANK_HASH_SECRET
              valueFrom:
                secretKeyRef:
                  key: hashSecret
                  name: {{ include "payment.fullname" . }}-bank
            - name: BANK_MID
              valueFrom:
                secretKeyRef:
                  key: mid
                  name: {{ include "payment.fullname" . }}-bank
            - name: BANK_NET_PAY_CANCLE
              valueFrom:
                secretKeyRef:
                  key: netPayCancle
                  name: {{ include "payment.fullname" . }}-bank
            - name: BANK_PAYMENT_INFO
              valueFrom:
                secretKeyRef:
                  key: paymentInfo
                  name: {{ include "payment.fullname" . }}-bank
            - name: BANK_PAY_CANCLE
              valueFrom:
                secretKeyRef:
                  key: payCancle
                  name: {{ include "payment.fullname" . }}-bank
            - name: BANK_PAY_APPROVE
              valueFrom:
                secretKeyRef:
                  key: payApprove
                  name: {{ include "payment.fullname" . }}-bank
            - name: BANK_TR_INFO
              valueFrom:
                secretKeyRef:
                  key: trInfo
                  name: {{ include "payment.fullname" . }}-bank
            - name: CARD_MID
              valueFrom:
                secretKeyRef:
                  key: mid
                  name: {{ include "payment.fullname" . }}-card
            - name: CARD_HYUNDAI_MID
              valueFrom:
                secretKeyRef:
                  key: hyundaiMid
                  name: {{ include "payment.fullname" . }}-card
            - name: CARD_EVENT_MID
              valueFrom:
                secretKeyRef:
                  key: eventMid
                  name: {{ include "payment.fullname" . }}-card
            - name: CARD_MERCHANT_KEY
              valueFrom:
                secretKeyRef:
                  key: merchantKey
                  name: {{ include "payment.fullname" . }}-card
            - name: CARD_HYUNDAI_MERCHANT_KEY
              valueFrom:
                secretKeyRef:
                  key: hyundaiMerchantKey
                  name: {{ include "payment.fullname" . }}-card
            - name: CARD_EVENT_MERCHANT_KEY
              valueFrom:
                secretKeyRef:
                  key: eventMerchantKey
                  name: {{ include "payment.fullname" . }}-card
            - name: CARD_CANCEL_PWD
              valueFrom:
                secretKeyRef:
                  key: cancelPwd
                  name: {{ include "payment.fullname" . }}-card
            - name: CARD_PAY_APPROVE_URL
              valueFrom:
                secretKeyRef:
                  key: payApproveUrl
                  name: {{ include "payment.fullname" . }}-card
            - name: CARD_PAY_CANCEL_URL
              valueFrom:
                secretKeyRef:
                  key: payCancelUrl
                  name: {{ include "payment.fullname" . }}-card
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: {{ include "payment.fullname" . }}-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ include "payment.fullname" . }}-database
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "payment.fullname" . }}-database
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: {{ include "payment.fullname" . }}-database
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: {{ include "payment.fullname" . }}-database
            - name: DB_ENGINE
              valueFrom:
                secretKeyRef:
                  key: engine
                  name: {{ include "payment.fullname" . }}-database
            - name: DB_POOL_SIZE
              valueFrom:
                secretKeyRef:
                  key: poolSize
                  name: {{ include "payment.fullname" . }}-database
            - name: MIGRATE_RUN
              valueFrom:
                secretKeyRef:
                  key: migrateRun
                  name: {{ include "payment.fullname" . }}-database
            - name: ETHERS_ALCHEMY_KEY
              valueFrom:
                secretKeyRef:
                  key: apiKey
                  name: {{ include "payment.fullname" . }}-alchemy
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: region
                  name: {{ include "payment.fullname" . }}-aws-credentials
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: accessKey
                  name: {{ include "payment.fullname" . }}-aws-credentials
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: {{ include "payment.fullname" . }}-aws-credentials
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_PROFILING_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: ddProfilingEnabled
                  name: {{ include "payment.fullname" . }}-datadog
            - name: DD_LOGS_INJECTION
              valueFrom:
                configMapKeyRef:
                  key: ddLogsInjectionEnabled
                  name: {{ include "payment.fullname" . }}-datadog
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 60
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}