apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wallet-api.fullname" . }}
  labels:
    {{- include "wallet-api.labels" . | nindent 4 }}
    {{- include "wallet-api.datadogLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wallet-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wallet-api.selectorLabels" . | nindent 8 }}
        {{- include "wallet-api.datadogSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: dbHost
                  name: {{ include "wallet-api.fullname" . }}-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: dbUser
                  name: {{ include "wallet-api.fullname" . }}-db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: dbPassword
                  name: {{ include "wallet-api.fullname" . }}-db
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: dbDatabase
                  name: {{ include "wallet-api.fullname" . }}-db
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: dbPort
                  name: {{ include "wallet-api.fullname" . }}-db
            - name: DB_ENGINE
              valueFrom:
                secretKeyRef:
                  key: dbEngine
                  name: {{ include "wallet-api.fullname" . }}-db
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: awsRegion
                  name: {{ include "wallet-api.fullname" . }}-aws
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: awsAccessKey
                  name: {{ include "wallet-api.fullname" . }}-aws
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: awsSecretKey
                  name: {{ include "wallet-api.fullname" . }}-aws
            - name: AWS_WALLET_CREATE_NOTIFICATION_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: awsWalletCreateNotificationQueueName
                  name: {{ include "wallet-api.fullname" . }}-aws
            - name: AWS_WALLET_CREATE_NOTIFICATION_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: awsWalletCreateNotificationQueueUrl
                  name: {{ include "wallet-api.fullname" . }}-aws
            - name: AWS_USER_WALLET_TRANSACTION_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: awsUserWalletTransactionQueueName
                  name: {{ include "wallet-api.fullname" . }}-aws
            - name: AWS_USER_WALLET_TRANSACTION_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: awsUserWalletTransactionQueueUrl
                  name: {{ include "wallet-api.fullname" . }}-aws
            - name: OCTET_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: octetApiToken
                  name: {{ include "wallet-api.fullname" . }}-octet
            - name: OCTET_BASE_URL
              valueFrom:
                secretKeyRef:
                  key: octetBaseUrl
                  name: {{ include "wallet-api.fullname" . }}-octet
            - name: WALLET_IDX
              valueFrom:
                secretKeyRef:
                  key: walletIdx
                  name: {{ include "wallet-api.fullname" . }}-octet
            - name: OCTET_DELEGATE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: delegateApiToken
                  name: {{ include "wallet-api.fullname" . }}-delegate
            - name: OCTET_DELEGATE_WALLET_IDX
              valueFrom:
                secretKeyRef:
                  key: delegateWalletId
                  name: {{ include "wallet-api.fullname" . }}-delegate
            - name: OCTET_DELEGATE_CHILD_ADMIN_ADDRESS
              valueFrom:
                secretKeyRef:
                  key: delegateChildAdminAddress
                  name: {{ include "wallet-api.fullname" . }}-delegate
            - name: MAXIMUM_DELEGATE_GAS_PRICE
              valueFrom:
                secretKeyRef:
                  key: delegateMaximumGasPrice
                  name: {{ include "wallet-api.fullname" . }}-delegate
            - name: MAXIMUM_DELEGATE_COUNT_PER_DAY
              valueFrom:
                secretKeyRef:
                  key: delegateMaximumCountPerDay
                  name: {{ include "wallet-api.fullname" . }}-delegate
            - name: RECOVERY_PIN
              valueFrom:
                secretKeyRef:
                  key: recoveryPin
                  name: {{ include "wallet-api.fullname" . }}-octet
            - name: ALCHEMY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: alchemyApiKey
                  name: {{ include "wallet-api.fullname" . }}-alchemy
            - name: ALCHEMY_HOST
              valueFrom:
                secretKeyRef:
                  key: alchemyHost
                  name: {{ include "wallet-api.fullname" . }}-alchemy
            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  key: jwtExpiresIn
                  name: {{ include "wallet-api.fullname" . }}-jwt
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwtSecret
                  name: {{ include "wallet-api.fullname" . }}-jwt
            - name: JWT_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwtAuthSecret
                  name: {{ include "wallet-api.fullname" . }}-jwt
            - name: HASH_IDS_KEY
              valueFrom:
                secretKeyRef:
                  key: hashIdsKey
                  name: {{ include "wallet-api.fullname" . }}-encoding
            - name: RSA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: rsaPrivateKey
                  name: {{ include "wallet-api.fullname" . }}-encoding
            - name: RSA_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: rsaPublicKey
                  name: {{ include "wallet-api.fullname" . }}-encoding
            - name: CHAIN_ID
              valueFrom:
               configMapKeyRef:
                  key: chainId
                  name: {{ include "wallet-api.fullname" . }}-common
            - name: ETHEREUM_BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  key: ethereumBackendHost
                  name: {{ include "wallet-api.fullname" . }}-common
            - name: POLYGON_BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  key: polygonBackendHost
                  name: {{ include "wallet-api.fullname" . }}-common
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_PROFILING_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: ddProfilingEnabled
                  name: {{ include "wallet-api.fullname" . }}-datadog
            - name: DD_LOGS_INJECTION
              valueFrom:
                configMapKeyRef:
                  key: ddLogsInjectionEnabled
                  name: {{ include "wallet-api.fullname" . }}-datadog
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
