apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}-aws
data:
  newAccountReportQueueUrl: {{ default "" .Values.config.aws.newAccountReportQueueUrl | quote }}
  walletCreateNotificationQueueName: {{ default "" .Values.config.aws.walletCreateNotificationQueueName | quote }}
  walletCreateNotificationQueueUrl: {{ default "" .Values.config.aws.walletCreateNotificationQueueUrl | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}-common
data:
  nonceTemplate: {{ default "" .Values.config.common.nonceTemplate | b64enc | quote }}
  tosUrl: {{ default "" .Values.config.common.tosUrl | quote }}
  tosUpdated: {{ default "" .Values.config.common.tosUpdated | quote }}
  walletBackendBaseUrl: {{ default "" .Values.config.common.walletBackendBaseUrl | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}-identity
data:
  identityDanalApiBase: {{ default "" .Values.config.identity.identityDanalApiBase | quote }}
  identityDanalTargetUrl: {{ default "" .Values.config.identity.identityDanalTargetUrl | quote }}
  identityUserDanalTargetUrl: {{ default "" .Values.config.identity.identityUserDanalTargetUrl | quote }}
  identityResetPinDanalTargetUrl: {{ default "" .Values.config.identity.identityResetPinDanalTargetUrl | quote }}
  identityOauthClientId: {{ default "" .Values.config.identity.identityOauthClientId | quote }}
  identityValidRedirectUrls: {{ default "" .Values.config.identity.identityValidRedirectUrls | quote }}
  identityHomePage: {{ default "" .Values.config.identity.identityHomePage | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}-datadog
data:
  ddProfilingEnabled: {{ default "" .Values.config.datadog.ddProfilingEnabled | quote }}
  ddLogsInjectionEnabled: {{ default "" .Values.config.datadog.ddLogsInjectionEnabled | quote }}