apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
    {{- include "auth.datadogLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth.selectorLabels" . | nindent 8 }}
        {{- include "auth.datadogSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AUTHLIB_INSECURE_TRANSPORT
              value: "1"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_ENGINE
              valueFrom:
                secretKeyRef:
                  key: engine
                  name: {{ include "auth.fullname" . }}-database
            - name: OAUTH2_TOKEN_EXPIRES_IN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: oauth2TokenExpiresInPassword
                  name: {{ include "auth.fullname" . }}-oauth
            - name: OAUTH2_REFRESH_TOKEN_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  key: oauth2RefreshTokenExpiresIn
                  name: {{ include "auth.fullname" . }}-oauth
            - name: OAUTH2_CODE_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  key: oauth2CodeExpiresIn
                  name: {{ include "auth.fullname" . }}-oauth
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: {{ include "auth.fullname" . }}-oauth
            - name: RESET_PIN_JWT_EXP
              valueFrom:
                secretKeyRef:
                  key: resetPinJwtExp
                  name: {{ include "auth.fullname" . }}-oauth
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: awsRegion
                  name: {{ include "auth.fullname" . }}-aws
            - name: AWS_ACCESS_KEY
              valueFrom:
               secretKeyRef:
                  key: awsAccessKey
                  name: {{ include "auth.fullname" . }}-aws
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: awsSecretKey
                  name: {{ include "auth.fullname" . }}-aws
            - name: NEW_ACCOUNT_REPORT_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: newAccountReportQueueUrl
                  name: {{ include "auth.fullname" . }}-aws
            - name: AWS_WALLET_CREATE_NOTIFICATION_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: walletCreateNotificationQueueName
                  name: {{ include "auth.fullname" . }}-aws
            - name: AWS_WALLET_CREATE_NOTIFICATION_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: walletCreateNotificationQueueUrl
                  name: {{ include "auth.fullname" . }}-aws
            - name: NONCE_TEMPLATE
              valueFrom:
                configMapKeyRef:
                  key: nonceTemplate
                  name: {{ include "auth.fullname" . }}-common
            - name: TOS_URL
              valueFrom:
                configMapKeyRef:
                  key: tosUrl
                  name: {{ include "auth.fullname" . }}-common
            - name: TOS_UPDATED
              valueFrom:
                configMapKeyRef:
                  key: tosUpdated
                  name: {{ include "auth.fullname" . }}-common
            - name: IDENTITY_DANAL_API_BASE
              valueFrom:
                configMapKeyRef:
                  key: identityDanalApiBase
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_DANAL_CPID
              valueFrom:
                secretKeyRef:
                  key: identityDanalCPID
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_DANAL_CPPWD
              valueFrom:
                secretKeyRef:
                  key: identityDanalCPPWD
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_DANAL_TARGET_URL
              valueFrom:
                configMapKeyRef:
                  key: identityDanalTargetUrl
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_USER_DANAL_TARGET_URL
              valueFrom:
                configMapKeyRef:
                  key: identityUserDanalTargetUrl
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_RESET_PIN_DANAL_TARGET_URL
              valueFrom:
                configMapKeyRef:
                  key: identityResetPinDanalTargetUrl
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_VALID_REDIRECT_URLS
              valueFrom:
                secretKeyRef:
                  key: identityValidRedirectUrls
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_OAUTH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: identityOauthClientId
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  key: identityEncryptKey
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_HOME_PAGE
              valueFrom:
                configMapKeyRef:
                  key: identityHomePage
                  name: {{ include "auth.fullname" . }}-identity
            - name: SOCIAL_LOGIN_APPLE_APP_ID
              valueFrom:
                secretKeyRef:
                  key: socialLoginAppleAppId
                  name: {{ include "auth.fullname" . }}-social
            - name: WALLET_BACKEND_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: walletBackendBaseUrl
                  name: {{ include "auth.fullname" . }}-common
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_PROFILING_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: ddProfilingEnabled
                  name: {{ include "auth.fullname" . }}-datadog
            - name: DD_LOGS_INJECTION
              valueFrom:
                configMapKeyRef:
                  key: ddLogsInjectionEnabled
                  name: {{ include "auth.fullname" . }}-datadog
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth.fullname" . }}-worker
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - flask
            - handle-internal-wallet-created
          env:
            - name: AUTHLIB_INSECURE_TRANSPORT
              value: "1"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_ENGINE
              valueFrom:
                secretKeyRef:
                  key: engine
                  name: {{ include "auth.fullname" . }}-database
            - name: OAUTH2_TOKEN_EXPIRES_IN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: oauth2TokenExpiresInPassword
                  name: {{ include "auth.fullname" . }}-oauth
            - name: OAUTH2_REFRESH_TOKEN_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  key: oauth2RefreshTokenExpiresIn
                  name: {{ include "auth.fullname" . }}-oauth
            - name: OAUTH2_CODE_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  key: oauth2CodeExpiresIn
                  name: {{ include "auth.fullname" . }}-oauth
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: {{ include "auth.fullname" . }}-oauth
            - name: RESET_PIN_JWT_EXP
              valueFrom:
                secretKeyRef:
                  key: resetPinJwtExp
                  name: {{ include "auth.fullname" . }}-oauth
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: awsRegion
                  name: {{ include "auth.fullname" . }}-aws
            - name: AWS_ACCESS_KEY
              valueFrom:
               secretKeyRef:
                  key: awsAccessKey
                  name: {{ include "auth.fullname" . }}-aws
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: awsSecretKey
                  name: {{ include "auth.fullname" . }}-aws
            - name: NEW_ACCOUNT_REPORT_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: newAccountReportQueueUrl
                  name: {{ include "auth.fullname" . }}-aws
            - name: AWS_WALLET_CREATE_NOTIFICATION_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: walletCreateNotificationQueueName
                  name: {{ include "auth.fullname" . }}-aws
            - name: AWS_WALLET_CREATE_NOTIFICATION_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: walletCreateNotificationQueueUrl
                  name: {{ include "auth.fullname" . }}-aws
            - name: NONCE_TEMPLATE
              valueFrom:
                configMapKeyRef:
                  key: nonceTemplate
                  name: {{ include "auth.fullname" . }}-common
            - name: TOS_URL
              valueFrom:
                configMapKeyRef:
                  key: tosUrl
                  name: {{ include "auth.fullname" . }}-common
            - name: TOS_UPDATED
              valueFrom:
                configMapKeyRef:
                  key: tosUpdated
                  name: {{ include "auth.fullname" . }}-common
            - name: IDENTITY_DANAL_API_BASE
              valueFrom:
                configMapKeyRef:
                  key: identityDanalApiBase
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_DANAL_CPID
              valueFrom:
                secretKeyRef:
                  key: identityDanalCPID
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_DANAL_CPPWD
              valueFrom:
                secretKeyRef:
                  key: identityDanalCPPWD
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_DANAL_TARGET_URL
              valueFrom:
                configMapKeyRef:
                  key: identityDanalTargetUrl
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_USER_DANAL_TARGET_URL
              valueFrom:
                configMapKeyRef:
                  key: identityUserDanalTargetUrl
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_RESET_PIN_DANAL_TARGET_URL
              valueFrom:
                configMapKeyRef:
                  key: identityResetPinDanalTargetUrl
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_VALID_REDIRECT_URLS
              valueFrom:
                configMapKeyRef:
                  key: identityValidRedirectUrls
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_OAUTH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: identityOauthClientId
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  key: identityEncryptKey
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_HOME_PAGE
              valueFrom:
                configMapKeyRef:
                  key: identityHomePage
                  name: {{ include "auth.fullname" . }}-identity
            - name: SOCIAL_LOGIN_APPLE_APP_ID
              valueFrom:
                secretKeyRef:
                  key: socialLoginAppleAppId
                  name: {{ include "auth.fullname" . }}-social
            - name: WALLET_BACKEND_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: walletBackendBaseUrl
                  name: {{ include "auth.fullname" . }}-common
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_PROFILING_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: ddProfilingEnabled
                  name: {{ include "auth.fullname" . }}-datadog
            - name: DD_LOGS_INJECTION
              valueFrom:
                configMapKeyRef:
                  key: ddLogsInjectionEnabled
                  name: {{ include "auth.fullname" . }}-datadog
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
