apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-database
type: Opaque
data:
  host: {{ default "" .Values.secret.database.host | b64enc | quote }}
  user: {{ default "" .Values.secret.database.user | b64enc | quote }}
  port: {{ default "" .Values.secret.database.port | b64enc | quote }}
  password: {{ default "" .Values.secret.database.password | b64enc | quote }}
  database: {{ default "" .Values.secret.database.database | b64enc | quote }}
  engine: {{ default "" .Values.secret.database.engine | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-aws
type: Opaque
data:
  awsRegion: {{ default "" .Values.secret.aws.awsRegion | b64enc | quote }}
  awsAccessKey: {{ default "" .Values.secret.aws.awsAccessKey | b64enc | quote }}
  awsSecretKey: {{ default "" .Values.secret.aws.awsSecretKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-oauth
data:
  oauth2TokenExpiresInPassword: {{ default "" .Values.secret.oauth.oauth2TokenExpiresInPassword | b64enc | quote }}
  oauth2RefreshTokenExpiresIn: {{ default "" .Values.secret.oauth.oauth2RefreshTokenExpiresIn | b64enc | quote }}
  secretKey: {{ default "" .Values.secret.oauth.secretKey | b64enc | quote }}
  resetPinJwtExp: {{ default "" .Values.secret.oauth.resetPinJwtExp | b64enc | quote }}
  oauth2CodeExpiresIn: {{ default "" .Values.secret.oauth.oauth2CodeExpiresIn | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-identity
data:
  identityDanalCPID: {{ default "" .Values.secret.identity.identityDanalCPID | b64enc | quote }}
  identityDanalCPPWD: {{ default "" .Values.secret.identity.identityDanalCPPWD | b64enc | quote }}
  identityEncryptKey: {{ default "" .Values.secret.identity.identityEncryptKey | b64enc | quote }}
  identityValidRedirectUrls: {{ default "" .Values.secret.identity.identityValidRedirectUrls | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-social
data:
  socialLoginAppleAppId: {{ default "" .Values.secret.social.socialLoginAppleAppId | b64enc | quote }}


