{{- if .Values.ingress.enabled -}}
apiVersion: configuration.konghq.com/v1
config:
  origins:
  - '*'
kind: KongPlugin
metadata:
  name: {{ include "wallet-api.cors" . }}
plugin: cors
---
apiVersion: configuration.konghq.com/v1
config:
  authMethod: client_secret_basic
  authResponseHeadersToForward:
  - sub
  - current-address
  clientId: {{ default "" .Values.config.oauth.clientId | quote }}
  clientSecret: {{ default "" .Values.config.oauth.clientSecret | quote }}
  tokenIntrospectUrl: {{ default "" .Values.config.oauth.tokenIntrospectUrl | quote }}

kind: KongPlugin
metadata:
  name: {{ include "wallet-api.validateAuthServerToken" . }}
plugin: oauth2-token-introspection-request
{{- end }}
