apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strapi.secretNameForDB" . }}
type: Opaque
data:
  host: {{ default "" .Values.secret.database.host | b64enc | quote }}
  engine: {{ default "" .Values.secret.database.engine | b64enc | quote }}
  database: {{ default "" .Values.secret.database.database | b64enc | quote }}
  password: {{ default "" .Values.secret.database.password | b64enc | quote }}
  port: {{ default "" .Values.secret.database.port | b64enc | quote }}
  user: {{ default "" .Values.secret.database.user | b64enc | quote }}
  pool_size: {{ default "" .Values.secret.database.pool_size | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strapi.secretNameForAWS" . }}
type: Opaque
data:
  accessKey: {{ default "" .Values.secret.aws.accessKey | b64enc | quote }}
  accessSecret: {{ default "" .Values.secret.aws.accessSecret | b64enc | quote }}