apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-common
data:
  ethreumNetwork: {{ default "" .Values.config.backend.ethreumNetwork | quote }}
  marketplaceNftAddress: {{ default "" .Values.config.backend.marketplaceNftAddress | quote }}
  networkProvider: {{ default "" .Values.config.backend.networkProvider | quote }}
  eventListenerHost: {{ default "" .Values.config.eventListenerHost | quote }}
  accountApiBaseUrl: {{ default "" .Values.config.backend.accountApiBaseUrl | quote }}
  chainId: {{ default "" .Values.config.backend.chainId | quote }}
  paymentHost: {{ default "" .Values.config.backend.paymentHost | quote }}
  originalsHost: {{ default "" .Values.config.backend.originalsHost | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-aws-queue
data:
  collectionQueueName: {{ default "" .Values.config.aws.queue.collectionQueueName | quote }}
  collectionQueueUrl: {{ default "" .Values.config.aws.queue.collectionQueueUrl | quote }}
  refreshItemMetaQueueName: {{ default "" .Values.config.aws.queue.refreshItemMetaQueueName | quote }}
  refreshItemMetaQueueUrl: {{ default "" .Values.config.aws.queue.refreshItemMetaQueueUrl | quote }}
  orderCancelledQueueName: {{ default "" .Values.config.aws.queue.orderCancelledQueueName | quote }}
  orderCancelledQueueUrl: {{ default "" .Values.config.aws.queue.orderCancelledQueueUrl | quote }}
  orderFulfilledQueueName: {{ default "" .Values.config.aws.queue.orderFulfilledQueueName | quote }}
  orderFulfilledQueueUrl: {{ default "" .Values.config.aws.queue.orderFulfilledQueueUrl | quote }}
  rapidCrawlingCollectionQueueName: {{ default "" .Values.config.aws.queue.rapidCrawlingCollectionQueueName | quote }}
  rapidCrawlingCollectionQueueUrl: {{ default "" .Values.config.aws.queue.rapidCrawlingCollectionQueueUrl | quote }}
  rapidCrawlingItemQueueName: {{ default "" .Values.config.aws.queue.rapidCrawlingItemQueueName | quote }}
  rapidCrawlingItemQueueUrl: {{ default "" .Values.config.aws.queue.rapidCrawlingItemQueueUrl | quote }}
  rapidCrawlingRefreshItemMetaQueueName: {{ default "" .Values.config.aws.queue.rapidCrawlingRefreshItemMetaQueueName | quote }}
  rapidCrawlingRefreshItemMetaQueueUrl: {{ default "" .Values.config.aws.queue.rapidCrawlingRefreshItemMetaQueueUrl | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-aws-s3
data:
  s3BucketCollection: {{ default "" .Values.config.aws.s3.s3BucketCollection | quote }}
  s3BucketItem: {{ default "" .Values.config.aws.s3.s3BucketItem | quote }}
  s3KeyMainImage: {{ default "" .Values.config.aws.s3.s3KeyMainImage | quote }}
  s3KeyBackgroundImage: {{ default "" .Values.config.aws.s3.s3KeyBackgroundImage | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-contract
data:
  marketplace: {{ default "" .Values.config.contractAddress.market | quote }}
  weth: {{ default "" .Values.config.contractAddress.weth | quote }}
  usdc: {{ default "" .Values.config.contractAddress.usdc | quote }}
  wmatic: {{ default "" .Values.config.contractAddress.wmatic | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-datadog
data:
  ddProfilingEnabled: {{ default "" .Values.config.datadog.ddProfilingEnabled | quote }}
  ddLogsInjectionEnabled: {{ default "" .Values.config.datadog.ddLogsInjectionEnabled | quote }}